# #Algorithm 2
# numlist = []
# for i in range(1001):
#     if i%3 == 0 or i%5 == 0:
#         numlist.append(i)

# print(sum(numlist))

#Algorithm 3
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


# fiblist = [1,2,3,5]
# while i < 4000000:
#     i += (sum(range(fiblist[i],fiblist[i-2])
#     fiblist.append(i)

# print(sum(fiblist))

# Algorithm 4
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143 

primes =[]
n = 600851475143
p = 2
while n >= p**2:
    if n%p == 0:
        primes.append(p)
        n /= p
    else:
        p += 1

print(n)
